---
title: "FAQ"
image: string
comments: false
callout-icon: true
callout-appearance: "default"
filters: 
 - callouts.lua
---

::: {.callout-note collapse=false}
## This website is still under active development! {{< fa wrench >}}
We are continuously updating information on this website.
Watch this space for any updates.
If you have any urgent questions, always feel free to write an [email]({{< var links.mailto >}}).
Thank you for your patience!
:::

## Participation

::: {.callout-tip}
## Can I participate online?
This is still being discussed.
Watch this space for any updates.
:::

::: {.callout-tip}
## Who can participate in the course?
The course is targeted at Master's and PhD students in Psychology and Cognitive Neuroscience.
:::

::: {.callout-tip}
## Do I have to be a student at the University of Hamburg in order to participate?
This is still being discussed.
Watch this space for any updates.
:::

## Course

::: {.callout-tip}
## When will the course take place?
The course will take place in the Winter semester 2023/24.
The lecture period is from 9 October 2023 to 27 January 2024.
The exact times and dates will be announced soon.
:::

::: {.callout-tip}
## Where will the course take place?
The course will take place at the [Institute of Psychology](https://www.psy.uni-hamburg.de/en.html) at the [University of Hamburg](https://www.uni-hamburg.de/en.html).
The exact room will be announced soon.
:::
