---
title: "Mechanics: Course Overview"
comments: false
nocite: |
  @wilson2021, @millman2018
---

## Overview

:::: {.columns}
::: {.column width="50%"}
{{< fa calendar-days >}} **Date:** Winter semester 2023/24 (Oct to Feb)
:::
::: {.column width="50%"}
{{< fa chalkboard >}} **Event:** Seminar
:::
::: {.column width="50%"}
{{< fa clock >}} **Time:** Fridays, 10:15 to 11:45 am (90 minutes)
:::
::: {.column width="50%"}
{{< fa gem >}} **Credits:** 4,0
:::
::: {.column width="50%"}
{{< fa building-columns >}} **Room:** UHH, VMP 5, Room 4047
:::
::: {.column width="50%"}
{{< fa language >}} **Language:** English / German
:::
::: {.column width="50%"}
{{< fa person-chalkboard >}} **Instructor:** [Dr. Lennart Wittkuhn]({{< var team.lennart.website >}})
:::
::: {.column width="50%"}
{{< fa tag >}} **Tag:** PsyM14-PsyWB-K02 
:::
::: {.column width="100%"}
{{< fa file-signature >}} **Registration:** The registration period starts on September 4th 2023 at 9:00 and ends on September 21th 2023 at 13:00.
MSc Psychology students at University of Hamburg can enroll via [Stine]({{< var links.stine >}}).
:::
::::

## What will the average seminar session look like?

The course will consist of a maximum of 14 sessions, each lasting 90 minutes (for more details, refer to the [schedule](schedule.qmd)).
Each course session follows a roughly structured format as outlined below:

1. {{< fa book-open >}} **Content Review (up to 30 minutes):**
<br> Course participants engage with [the online materials](https://lennartwittkuhn.com/version-control-book/), supplemented by concise presentations by the instructors.
Some course preparation may occur outside of the class.
   
2. {{< fa comments >}} **Interactive Discussions & Quizzes (up to 15 minutes):**
<br>Course participants collectively address any inquiries related to the session's content and online materials.
Instructor-led quiz questions may also be interspersed throughout.

3. {{< fa laptop-code >}} **Exercises & Implementation (up to 60 minutes):**
<br>Course participants actively delve into hands-on exercises and assignments.

Note, that course participants are **not required** (but are of course free) **to work on course materials outside of class time**.
All course contents will be covered during class time.

## Summary of course mechanics

This course will be conducted in person, but all [course materials](#course-materials) will be available online.
The course follows a [partially flipped classroom](#partially-flipped-classroom) and [active learning](#active-learning) approach, which means that students will learn the [content](#course-materials) outside of class and engage in [assignments](#assignments) during class.

## Partially Flipped Classroom

The flipped classroom is an educational approach where **students learn the instructional content outside of class** (e.g., through videos or online resources) and **use class time for interactive activities**, discussions, and collaboration.
In this course, students will have the opportunity to learn at home using the available [course materials](#course-materials).
We will, however, reserve time in the beginning of each class (roughly 15 - 30 minutes of 90 minutes) to allow all course participants to catch up with the content of the current session.
The rest of the class time is dedicated to discussion, exercises implementation.

## Course Materials

### Textbook: Version Control Book

In preparation for each seminar session, students will be asked to study specific chapters in the [Version Control Book](https://lennartwittkuhn.com/version-control-book/).
The Version Control Book aims to summarize all the relevant course contents for the students, effectively serving as a textbook for the course.
In addition, we will provide references to multiple other learning resources, allowing students to pick from those learning resources that they feel supports their learning process best.

## Prerequisites

There are no prerequisites to take part in this course.
Programming experience (any language) can be beneficial but is not required to follow the course contents.

## Active Learning

Active learning in this class involves engaging in **hands-on coding activities during class time**.
Research on active learning indicates that this approach promotes a greater understanding and retention of the material compared to passive teaching methods [see e.g., @deslauriers2019].

## Assignments

Students will work on assignments (individually or in [pairs](#pair-programming) during class.

## Pair Programming

> Pair programming is a software development technique in which two programmers work together at one workstation.
One, the driver, writes code while the other, the observer or navigator [@williams2001], reviews each line of code as it is typed in.
The two programmers switch roles frequently.
-- Source: [Wikipedia](https://en.wikipedia.org/wiki/Pair_programming)

## Implementation

> "*For training to have an impact, students must implement what they've 
learned in their own research.*" [@weissgerber2023]

@heise2023 outline actions that course organizers can take to prepare and support course participants in implementing what they have learned once they return to their research environment.

On [this page](implementation.qmd) we consider how to apply the recommendations by @heise2023 to our course in detail.

## Module

This course will be offered as part of the "Psychologischer Wahlbereich" module of the [M.Sc. Psychology (Research, as of WiSe 23/24)](https://www.psy.uni-hamburg.de/en/studium/studiengaenge/msc-psychology-research.html) at the University of Hamburg.

> The Master of Science in Psychology is a consecutive program that is strongly research-oriented.
The regular period of study is 4 semesters.
Teaching language is primarily English.
The degree program comprises 8 modules with 2 complementary areas of concentration.

>  Im "Psychologischen Wahlbereich" werden Veranstaltungen zu wechselnden Themen der Psychologie angeboten.
Darüber hinaus können Studierende Module oder einzelne für den Wahlbereich geöffnete Lehrveranstaltungen aus den Modulen C. und D., die sie nicht im Rahmen ihres Grundlagen- oder Anwendungswahlfaches belegt haben, besuchen.

<details>
<summary>Click here to view the **full module description** (in German).</summary><br>
```{=html}
<iframe width="100%" height="1200" src="images/20211110-fsb-pb-msc-psychologie-19-wahlpflicht.pdf"></iframe>
```
</details>

## References

:::{#refs}
:::